import './index.scss';
// import './demo/three';
// import './demo/react';
// import './demo/three';
// import './demo/area';
// import './demo/map';
// import './demo/zrender';
// import './demo/drawImage';
// import './demo/gaode';
import './demo/d3/d3';
